universe = vanilla

initialdir = /nethome/tadhopavkar/Concept-aware-vision-encoder/logs
executable = run_probe.sh
output = /nethome/tadhopavkar/Concept-aware-vision-encoder/logs/probe_$(ClusterId)_$(ProcId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error  = /nethome/tadhopavkar/Concept-aware-vision-encoder/logs/probe_$(ClusterId)_$(ProcId)$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log    = /nethome/tadhopavkar/Concept-aware-vision-encoder/logs/probe_$(ClusterId)$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log

request_cpus   = 8
request_memory = 32GB
request_gpus   = 1

# Usually appropriate when the project and environment are on shared storage
should_transfer_files = NO

getenv = True

queue 1